/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./erc20.sol";
export type { erc20Sol };
import type * as erc721Sol from "./erc721.sol";
export type { erc721Sol };
export type { Lock } from "./Lock";
